/**
 * \file ayb_help.h
 * Help text for AYB.
 */

"12345678901234567890123456789012345678901234567890123456789012345678901234567890\n"
"\n"
"Options:\n"
"  -b  --blockstring <Rn[InCn...]>\n"
"\tHow to group cycle data in intensity files for analysis [required]\n"
"\t(R=Read, I=Ignore, C=Concatenate onto previous block)\n"
"\t(First R must precede first C)\n\n"
"  -x  --prefix <path>\t\tFilter input files by match to prefix [required]\n"
"  -f  --format <format>\t\tOutput format [default: fasta]\n"
"\t\t\t\t(fasta/fastq)\n"
"  -n  --niter <num>\t\tNumber of model iterations [default: 5]\n"
"  -i  --input <path>\t\tLocation of input files [default: \"\"]\n"
"  -o  --output <path>\t\tLocation to create output files [default: \"\"]\n"
"  -e  --logfile <path>\t\tLocation of message output [default: none]\n"
"\t\t\t\t(Alternative to script redirect of error output)\n"
"  -l  --loglevel <level>\tLevel of message output [default: warning]\n"
"\t\t\t\t(none/fatal/error/warning/information/debug)\n"
"  -M  --M <filepath>\t\tPredetermined Crosstalk matrix file path\n"
"  -P  --P <filepath>\t\tPredetermined Phasing matrix file path\n"
"  -N  --N <filepath>\t\tPredetermined Noise matrix file path\n"
"  -S  --solver <solver>\t\tLinear equation solver to use for P matrix\n"
"\n"
"  --help\t\t\tDisplay this help\n"
"  --licence\t\t\tDisplay AYB licence information\n"
"  --version\t\t\tDisplay AYB version information\n"
"\n"
